// <auto-generated />
using System;
using MaoNaMassa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaoNaMassa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("IX_Aulas_CursoId");

                    b.HasIndex("CursoId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("IX_Aulas_CursoId_Ordem");

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nota")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("IX_Avaliacoes_Data");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("IX_Avaliacoes_ServicoId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Avaliacoes_UsuarioId");

                    b.HasIndex("UsuarioId", "ServicoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Avaliacoes_UsuarioId_ServicoId");

                    b.ToTable("Avaliacoes", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoCertificado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCertificado")
                        .IsUnique()
                        .HasDatabaseName("IX_Certificados_CodigoCertificado");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("IX_Certificados_CursoId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Certificados_UsuarioId");

                    b.HasIndex("UsuarioId", "CursoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Certificados_UsuarioId_CursoId");

                    b.ToTable("Certificados", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Area")
                        .HasDatabaseName("IX_Cursos_Area");

                    b.HasIndex("Nivel")
                        .HasDatabaseName("IX_Cursos_Nivel");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AvaliacaoMedia")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Disponivel")
                        .HasDatabaseName("IX_Profissionais_Disponivel");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_Profissionais_UsuarioId");

                    b.ToTable("Profissionais", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespostaCorreta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("IX_Quizzes_CursoId");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.RespostaQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Correta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("IX_RespostasQuiz_QuizId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_RespostasQuiz_UsuarioId");

                    b.HasIndex("UsuarioId", "QuizId")
                        .IsUnique()
                        .HasDatabaseName("IX_RespostasQuiz_UsuarioId_QuizId");

                    b.ToTable("RespostasQuiz", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cidade")
                        .HasDatabaseName("IX_Servicos_Cidade");

                    b.HasIndex("DataPublicacao")
                        .HasDatabaseName("IX_Servicos_DataPublicacao");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("IX_Servicos_ProfissionalId");

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaInteresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cidade")
                        .HasDatabaseName("IX_Usuarios_Cidade");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email");

                    b.HasIndex("TipoUsuario")
                        .HasDatabaseName("IX_Usuarios_TipoUsuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Aula", b =>
                {
                    b.HasOne("MaoNaMassa.Domain.Entities.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("MaoNaMassa.Domain.Entities.Servico", "Servico")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaoNaMassa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("MaoNaMassa.Domain.Entities.Curso", "Curso")
                        .WithMany("Certificados")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaoNaMassa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Certificados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Profissional", b =>
                {
                    b.HasOne("MaoNaMassa.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Profissional")
                        .HasForeignKey("MaoNaMassa.Domain.Entities.Profissional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("MaoNaMassa.Domain.Entities.Curso", "Curso")
                        .WithMany("Quizzes")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.RespostaQuiz", b =>
                {
                    b.HasOne("MaoNaMassa.Domain.Entities.Quiz", "Quiz")
                        .WithMany("RespostasQuiz")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaoNaMassa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RespostasQuiz")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Servico", b =>
                {
                    b.HasOne("MaoNaMassa.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Servicos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("Certificados");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("RespostasQuiz");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Servico", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("MaoNaMassa.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Certificados");

                    b.Navigation("Profissional");

                    b.Navigation("RespostasQuiz");
                });
#pragma warning restore 612, 618
        }
    }
}
